const data = [
  {
    id: 'base',
    moduleFlag: 'base',
    moduleName: '商品',
    parentId: '0',
    moduleUrl: '',
    type: 1,
    icon: '',
    sort: 1,
    children: [
      {
        id: 'base-ware',
        moduleFlag: 'base-ware',
        moduleName: '商品管理',
        parentId: 'base',
        moduleUrl: '',
        type: 1,
        icon: 'icon-GJYLshangpinguanli',
        sort: 1,
        children: [
          {
            id: 'base-ware-list',
            moduleFlag: 'base-ware-list',
            moduleName: '商品列表',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/list',
            type: 2,
            icon: '',
            sort: 1,
            children: [
              {
                id: 'base-ware-list:view',
                moduleFlag: 'base-ware-list:view',
                moduleName: '查看',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-list:enable',
                moduleFlag: 'base-ware-list:enable',
                moduleName: '启用',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-list:disable',
                moduleFlag: 'base-ware-list:disable',
                moduleName: '停用',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 3,
                children: [],
              },
              {
                id: 'base-ware-list:export-ware',
                moduleFlag: 'base-ware-list:export-ware',
                moduleName: '导出商品',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 4,
                children: [],
              },
              {
                id: 'base-ware-list:add',
                moduleFlag: 'base-ware-list:add',
                moduleName: '新增商品',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 5,
                children: [],
              },
              {
                id: 'base-ware-list:export-drug',
                moduleFlag: 'base-ware-list:export-drug',
                moduleName: '导出药监局数据',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 6,
                children: [],
              },
              {
                id: 'base-ware-list:stop-ware',
                moduleFlag: 'base-ware-list:stop-ware',
                moduleName: '停购',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 7,
                children: [],
              },
              {
                id: 'base-ware-detail:ware-update',
                moduleFlag: 'base-ware-detail:ware-update',
                moduleName: '商品变更',
                parentId: 'base-ware-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 8,
                children: [],
              },
            ],
          },
          {
            id: 'base-ware-change-list',
            moduleFlag: 'base-ware-change-list',
            moduleName: '商品变更单',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/change/list',
            type: 2,
            icon: '',
            sort: 2,
            children: [
              {
                id: 'base-ware-change-list:view',
                moduleFlag: 'base-ware-change-list:view',
                moduleName: '查看',
                parentId: 'base-ware-change-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-change-detail:apply',
                moduleFlag: 'base-ware-change-detail:apply',
                moduleName: '提审',
                parentId: 'base-ware-change-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-change-detail:check',
                moduleFlag: 'base-ware-change-detail:check',
                moduleName: '审核',
                parentId: 'base-ware-change-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 3,
                children: [],
              },
              {
                id: 'base-ware-change-detail:revoke',
                moduleFlag: 'base-ware-change-detail:revoke',
                moduleName: '撤销审核',
                parentId: 'base-ware-change-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 4,
                children: [],
              },
            ],
          },
          {
            id: 'base-ware-tax-rate-list',
            moduleFlag: 'base-ware-tax-rate-list',
            moduleName: '税率税码变更单',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/tax-rate/list',
            type: 2,
            icon: '',
            sort: 3,
            children: [
              {
                id: 'base-ware-tax-rate-list:view',
                moduleFlag: 'base-ware-tax-rate-list:view',
                moduleName: '查看',
                parentId: 'base-ware-tax-rate-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-tax-rate-list:add',
                moduleFlag: 'base-ware-tax-rate-list:add',
                moduleName: '新建',
                parentId: 'base-ware-tax-rate-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-tax-rate-detail:apply',
                moduleFlag: 'base-ware-tax-rate-detail:apply',
                moduleName: '提审',
                parentId: 'base-ware-tax-rate-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 3,
                children: [],
              },
              {
                id: 'base-ware-tax-rate-detail:check',
                moduleFlag: 'base-ware-tax-rate-detail:check',
                moduleName: '审核',
                parentId: 'base-ware-tax-rate-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 4,
                children: [],
              },
              {
                id: 'base-ware-tax-rate-detail:revoke',
                moduleFlag: 'base-ware-tax-rate-detail:revoke',
                moduleName: '撤销审核',
                parentId: 'base-ware-tax-rate-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 5,
                children: [],
              },
              {
                id: 'base-ware-tax-rate-detail:close',
                moduleFlag: 'base-ware-tax-rate-detail:close',
                moduleName: '取消',
                parentId: 'base-ware-tax-rate-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 6,
                children: [],
              },
            ],
          },
          {
            id: 'base-ware-category',
            moduleFlag: 'base-ware-category',
            moduleName: '运营分类',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/category',
            type: 2,
            icon: '',
            sort: 4,
            children: [],
          },
          {
            id: 'base-ware-store-goods-list',
            moduleFlag: 'base-ware-store-goods-list',
            moduleName: '门店商品',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/store-goods/list',
            type: 2,
            icon: '',
            sort: 4,
            children: [
              {
                id: 'base-ware-store-goods-list:announce',
                moduleFlag: 'base-ware-store-goods-list:announce',
                moduleName: '批量发布门店',
                parentId: 'base-ware-store-goods-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-store-goods-list:downlog',
                moduleFlag: 'base-ware-store-goods-list:downlog',
                moduleName: '下架',
                parentId: 'base-ware-store-goods-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-store-goods-list:uplog',
                moduleFlag: 'base-ware-store-goods-list:uplog',
                moduleName: '上架',
                parentId: 'base-ware-store-goods-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-store-goods-list:view',
                moduleFlag: 'base-ware-store-goods-list:view',
                moduleName: '查看',
                parentId: 'base-ware-store-goods-list',
                moduleUrl: '',
                type: 3,
                icon: null,
                sort: 2,
                children: [],
              },
            ],
          },
          {
            id: 'base-ware-gspCategory-list',
            moduleFlag: 'base-ware-gspCategory-list',
            moduleName: '经营范围',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/gsp-category/list',
            type: 2,
            icon: '',
            sort: 6,
            children: [
              {
                id: 'base-ware-gspCategory-list:confirm',
                moduleFlag: 'base-ware-gspCategory-list:confirm',
                moduleName: '确认',
                parentId: 'base-ware-gspCategory-list',
                moduleUrl: '',
                type: 3,
                icon: null,
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-gspCategory-list:edit',
                moduleFlag: 'base-ware-gspCategory-list:edit',
                moduleName: '编辑',
                parentId: 'base-ware-gspCategory-list',
                moduleUrl: '',
                type: 3,
                icon: null,
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-gspCategory-list:view',
                moduleFlag: 'base-ware-gspCategory-list:view',
                moduleName: '查看',
                parentId: 'base-ware-gspCategory-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-gspCategory-list:add',
                moduleFlag: 'base-ware-gspCategory-list:add',
                moduleName: '新建分类',
                parentId: 'base-ware-gspCategory-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
            ],
          },
          {
            id: 'base-ware-enterprise-list',
            moduleFlag: 'base-ware-enterprise-list',
            moduleName: '生产企业资料',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/enterprise/list',
            type: 2,
            icon: '',
            sort: 7,
            children: [
              {
                id: 'base-ware-enterprise-list:view',
                moduleFlag: 'base-ware-enterprise-list:view',
                moduleName: '查看',
                parentId: 'base-ware-enterprise-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-enterprise-list:export',
                moduleFlag: 'base-ware-enterprise-list:export',
                moduleName: '导出',
                parentId: 'base-ware-enterprise-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
            ],
          },
          {
            id: 'base-ware-relation-list',
            moduleFlag: 'base-ware-relation-list',
            moduleName: '商品对应关系',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/relation/list',
            type: 2,
            icon: '',
            sort: 8,
            children: [
              {
                id: 'base-ware-relation-list:view',
                moduleFlag: 'base-ware-relation-list:view',
                moduleName: '查看',
                parentId: 'base-ware-relation-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-relation-list:import',
                moduleFlag: 'base-ware-relation-list:import',
                moduleName: '导入商品对应关系',
                parentId: 'base-ware-relation-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-relation-list:unbind',
                moduleFlag: 'base-ware-relation-list:unbind',
                moduleName: '解绑',
                parentId: 'base-ware-relation-list',
                moduleUrl: '',
                type: 3,
                icon: null,
                sort: 3,
                children: [],
              },
            ],
          },
          {
            id: 'base-ware-subscribe-list',
            moduleFlag: 'base-ware-subscribe-list',
            moduleName: '商品订阅',
            parentId: 'base-ware',
            moduleUrl: '/base/ware/subscribe/list',
            type: 2,
            icon: '',
            sort: 9,
            children: [
              {
                id: 'base-ware-subscribe-list:view',
                moduleFlag: 'base-ware-subscribe-list:view',
                moduleName: '查看',
                parentId: 'base-ware-subscribe-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 1,
                children: [],
              },
              {
                id: 'base-ware-subscribe-list:add',
                moduleFlag: 'base-ware-subscribe-list:add',
                moduleName: '新增',
                parentId: 'base-ware-subscribe-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 2,
                children: [],
              },
              {
                id: 'base-ware-subscribe-list:import',
                moduleFlag: 'base-ware-subscribe-list:import',
                moduleName: '批量导入',
                parentId: 'base-ware-subscribe-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 3,
                children: [],
              },
              {
                id: 'base-ware-subscribe-list:export',
                moduleFlag: 'base-ware-subscribe-list:export',
                moduleName: '导出',
                parentId: 'base-ware-subscribe-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 4,
                children: [],
              },
              {
                id: 'base-ware-subscribe-list:enable-disable',
                moduleFlag: 'base-ware-subscribe-list:enable-disable',
                moduleName: '停用/启用',
                parentId: 'base-ware-subscribe-list',
                moduleUrl: '',
                type: 3,
                icon: '',
                sort: 5,
                children: [],
              },
            ],
          },
        ],
      },
    ],
  },
];
export default data;
